[tool.poetry]
name = "actuals"
version = "0.1.0"
description = "Test runn API"
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [
 { include = "src" }
]

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.2.2"
pandas-gbq = "^0.23.1"
google-cloud-core = "^2.4.1"
google-cloud-bigquery = "^3.25.0"
google-cloud-secret-manager = "^2.20.0"
data_pipeline_tools = {git = "https://github.com/tpximpact/GCP-Data-Pipelines-DX.git", rev = "v1.0.3"}
#data_pipeline_tools = { path = "../../../", develop = true }
dotenv = "^0.9.9"


[tool.pyright]
extraPaths = ['../../../']


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pyright (>=1.1.406,<2.0.0)",
    "dotenv (>=0.9.9,<0.10.0)"
]
